---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters/finalizers
  verbs:
  - update
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters/status
  verbs:
  - get
  - patch
  - update
