# This rule is not used by the project butler-orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.butler.sh resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: butler-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: tenantcluster-viewer-role
rules:
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters/status
  verbs:
  - get
