# This rule is not used by the project butler-orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.butler.sh.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: butler-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: tenantcluster-admin-role
rules:
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters
  verbs:
  - '*'
- apiGroups:
  - core.butler.sh
  resources:
  - tenantclusters/status
  verbs:
  - get
