apiVersion: core.butler.sh/v1alpha1
kind: TenantCluster
metadata:
  name: tenantcluster-sample
spec:
  kubernetesVersion: v1.29.3
  provider:
    type: nutanix
    ref:
      apiVersion: infra.butler.sh/v1alpha1
      kind: NutanixCluster
      name: tenantcluster-sample-nutanix
  providerConfig:
    endpoint: https://prism.central.com
    username: admin
    passwordRef: nutanix-creds # Refers to a Kubernetes Secret
    clusterUUID: 00000000-0000-0000-0000-000000000000
    subnetUUID:  11111111-1111-1111-1111-111111111111
    nodes:
      - role: "control-plane"
        count: 3
        cpu: 4
        ram: "8Gi"
        disk: "50Gi"
        extraDisks:
          - diskSize: "100Gi"
        isoUUID: "abcd1234"
      - role: "worker"
        count: 2
        cpu: 2
        ram: "4Gi"
        disk: "50Gi"
        extraDisks:
          - diskSize: "100Gi"
